apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
      - name: backend
        image: hudsonfranca/anuncios-backend
        ports:
        - containerPort: 3000
        env:
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: db_user
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: db_host
          - name: PGPORT
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: db_port
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: database
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: db_password
          - name: JWT_KEY
            valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
          - name: EMAIL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: password
          - name: EMAIL_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: email-configmap
                key: email-address