apiVersion: v1
kind: PersistentVolume
metadata:
  name: persisten-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  